kind: pipeline
name: production

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: foo/bar
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    volumes:
    - name: docker
      path: /var/run/docker.sock 

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
